name: Build and Push BusyBox Image

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Harbor
      - name: Log in to Harbor
        run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login https://horborlab.enersys.io -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

     # Step 4:  Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: horborlab.enersys.io/harbor/projects/2/repositories/busybox:latest
        